spring:
  application:
    name: car-service

  datasource:
    url: jdbc:postgresql://${POSTGRES_HOST:localhost}:${POSTGRES_PORT:5432}/car_db
    username: ${POSTGRES_USER:rabbitride}
    password: ${POSTGRES_PASSWORD:rabbitride}

  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: true
    open-in-view: false

  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true

  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}
      timeout: 2s

  cache:
    type: redis
    redis:
      time-to-live: 300000   # 5 minutos

server:
  port: 8082

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: when_authorized

logging:
  level:
    com.gghiaroni.rabbitride: DEBUG
    org.springframework.web: INFO

app:
  security:
    admin-token: ${ADMIN_API_TOKEN:dev-admin-token-troque-em-prod}
    internal-token: ${INTERNAL_API_TOKEN:dev-internal-token-troque-em-prod}
