spring:
  application:
    name: notification-service

  rabbitmq:
    host: ${RABBITMQ_HOST:localhost}
    port: ${RABBITMQ_PORT:5672}
    username: ${RABBITMQ_USER:rabbitride}
    password: ${RABBITMQ_PASS:rabbitride}

  mail:
    host: ${SMTP_HOST:localhost}
    port: ${SMTP_PORT:1025}
    properties:
      mail:
        smtp:
          auth: false
          starttls:
            enable: false

server:
  port: 8085

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: when_authorized

logging:
  level:
    com.gghiaroni.rabbitride: DEBUG
    org.springframework.amqp: INFO
